build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
promotion:
  name: "4.15"
  namespace: ocp
releases:
  initial:
    integration:
      name: "4.15"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.15"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: .github/openshift-test-scripts/openshift-test-runner.sh
  container:
    from: src
zz_generated_metadata:
  branch: kabir-play
  org: wildfly
  repo: quickstart
